version: '3'
services:
  eum-frontend:
    build:
      context: eum-2.0/eum-frontend
    image: ${REPO}/eum/eum-frontend:${TAG}
  eum-ratings:
    build:
      context: eum-2.0/eum-ratings
    image: ${REPO}/eum/eum-ratings:${TAG}
  eum-shop:
    build:
      context: eum-2.0/eum-shop
    image: ${REPO}/eum/eum-shop:${TAG}
  eum-simulator:
    build:
      context: eum-2.0/eum-simulator
    image: ${REPO}/eum/eum-simulator:${TAG}
  eum-robotshop-server:
    build:
      context: eum-2.0/eum-robotshop-server
    image: ${REPO}/eum/eum-robotshop-server:${TAG}
  caller:
    build:
      context: caller-python
    image: ${REPO}/caller:${TAG}
  discount:
    build:
      context: discount
    image: ${REPO}/discount:${TAG}
  catalogue:
    build:
      context: catalogue
    image: ${REPO}/catalogue:${TAG}
    depends_on:
      - mongodb
    networks:
      - robot-shop
  mongodb:
    build:
      context: mongodb
    image: ${REPO}/mongodb:${TAG}
    networks:
      - robot-shop
  user:
    build:
      context: user
    image: ${REPO}/user:${TAG}
    depends_on:
      - mongodb
      - redis
    networks:
      - robot-shop
  cart:
    build:
      context: cart
    image: ${REPO}/cart:${TAG}
    depends_on:
      - redis
    networks:
      - robot-shop
  mysql:
    build:
      context: mysql
    image: ${REPO}/mysql-db:${TAG}
    cap_add:
      - NET_ADMIN
    networks:
      - robot-shop
  shipping:
    build:
      context: shipping
    image: ${REPO}/shipping:${TAG}
    depends_on:
      - mysql
    networks:
      - robot-shop
  ratings:
    build:
      context: ratings
    image: ${REPO}/ratings:${TAG}
    networks:
      - robot-shop
    depends_on:
      - mysql
  payment:
    build:
      context: payment
    image: ${REPO}/payment:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
    # Uncomment to change payment gateway
    #environment:
      #PAYMENT_GATEWAY: "https://www.worldpay.com"
  dispatch:
    build:
      context: dispatch
    image: ${REPO}/dispatch:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - robot-shop
  web:
    build:
      context: web
    image: ${REPO}/web:${TAG}
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - robot-shop
    # Uncomment to enable Instana EUM
    # environment:
      # INSTANA_EUM_KEY: <your eum key here>

networks:
  robot-shop:

