apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: catalogue
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - image: gcr.io/k8s-brewery/demo/catalogue:latest
          name: catalogue
          env:
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 600m
              memory: 800Mi
            requests:
              cpu: 300m
              memory: 400Mi
      restartPolicy: Always
