apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: catalogue
  name: catalogue
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: catalogue
    spec:
      containers:
        - image: gcr.io/k8s-brewery/robot-shop/rs-catalogue:latest
          name: catalogue
          env:
            - name: INSTANA_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 200Mi
      restartPolicy: Always
status: {}
