apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount
  labels:
    app: discount
spec:
  replicas: 3
  selector:
    matchLabels:
      app: discount
  template:
    metadata:
      labels:
        app: discount
    spec:
      containers:
        - name: discount
          image: gcr.io/k8s-brewery/robot-shop/rs-discount:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 400Mi
      restartPolicy: Always
status: {}
