apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount
  labels:
    app: discount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount
  template:
    metadata:
      labels:
        app: discount
    spec:
      containers:
        - name: discount
          image: gcr.io/k8s-brewery/robot-shop/rs-discount:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 300m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 800Mi
      restartPolicy: Always
status: {}