apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dispatch
  name: dispatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/dispatch:latest
        name: dispatch
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always
