apiVersion: v1
kind: Service
metadata:
  labels:
    app: dispatch
  name: dispatch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: dispatch
