apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-catalogue
  name: mongodb-catalogue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-catalogue
    spec:
      containers:
      - image: gcr.io/k8s-brewery/robot-shop/rs-mongodb-catalogue:latest
        name: mongodb-catalogue
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 150m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
      restartPolicy: Always
status: {}
