apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/mongodb:latest
        name: mongodb
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 150m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
      restartPolicy: Always
