apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/mysql-db:latest
        name: mysql
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 600m
            memory: 1400Mi
          requests:
            cpu: 300m
            memory: 1000Mi
      restartPolicy: Always
