apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/payment:latest
        name: payment
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 150Mi
      restartPolicy: Always
