apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion
  template:
    metadata:
      labels:
        app: promotion
    spec:
      containers:
        - name: promotion
          image: gcr.io/k8s-brewery/robot-shop/rs-promotion:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 600Mi
            requests:
              cpu: 50m
              memory: 400Mi
      restartPolicy: Always
status: {}