apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratings
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/ratings:latest
        name: ratings
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
      restartPolicy: Always
