apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings
  name: ratings
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: ratings
status:
  loadBalancer: {}
