apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shipping
  name: shipping
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/shipping:latest
        name: shipping
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 50m
            memory: 400Mi
      restartPolicy: Always
