apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user
  name: user
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
      - image: gcr.io/k8s-brewery/demo/user:latest
        name: user
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 150Mi
      restartPolicy: Always
