apiVersion: v1
kind: Service
metadata:
  labels:
    app: caller
  name: caller
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: caller
  type: LoadBalancer