apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: caller
  name: caller
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: caller
    spec:
      containers:
        - image: gcr.io/k8s-brewery/robot-shop/rs-caller:latest
          name: caller
          env:
            - name: SERVER_HOST
              value: "http://caller"
            - name: SERVER_PORT
              value: "8080"
            - name: WEB_HOST
              value: "http://web"
            - name: WEB_PORT
              value: "8080"
            - name: LOAD_CONCURRENCY
              value: "4"
            - name: LOAD_REQUESTS_PER_SECOND
              value: "2"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 600Mi
            requests:
              cpu: 400m
              memory: 400Mi
      restartPolicy: Always