apiVersion: v1
kind: Service
metadata:
  labels:
    app: es-caller
  name: caller
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: es-caller
  type: LoadBalancer
