apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: es-load
  name: es-load
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: es-load
    spec:
      containers:
      - image: gcr.io/k8s-brewery/es-apps/caller:latest
        name: load
        env:
          - name: HOST
            value: "http://catalogue:8080"
          - name: NUM_CLIENTS
            value: "1"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
