apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: caller
  name: caller
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: caller
    spec:
      containers:
        - image: gcr.io/k8s-brewery/robot-shop/rs-caller:latest
          name: caller
          env:
            - name: WEB_HOST
              value: "http://web:8080"
            - name: LOAD_CONCURRENCY
              value: "2"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 300m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 50Mi
      restartPolicy: Always
