apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
  selector:
    run: cassandra