apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: robot-shop
  labels:
    io.kompose.service: load
  name: load
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: load
    spec:
      containers:
      - image: gcr.io/k8s-brewery/robot-shop/rs-load:latest
        name: load
        env:
          - name: HOST
            value: "http://web:8080"
          - name: NUM_CLIENTS
            value: "10"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 300m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
      restartPolicy: Always
