apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion
  template:
    metadata:
      labels:
        app: promotion
    spec:
      containers:
      - name: promotion
        image: #image from gcr repo
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 600m
            memory: 400Mi
          requests:
            cpu: 300m
            memory: 200Mi
