apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: ratings
  name: ratings
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ratings
    spec:
      containers:
      - image: gcr.io/k8s-brewery/robot-shop/rs-ratings:latest
        name: ratings
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 300Mi
      restartPolicy: Always
status: {}
