apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: es-catalogue
  name: es-catalogue
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: es-catalogue
    spec:
      containers:
      - image: gcr.io/k8s-brewery/es-apps/catalogue:latest
        name: es-catalogue
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
status: {}
